import {webkit,chromium} from 'playwright';
import fs from 'node:fs/promises';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const E=createRequire(import.meta.url)('../engine.js'),url=process.env.BRIDGE_URL||'http://127.0.0.1:8801/',KEY='ai-bridge-game-v1',out=new URL('../output/playwright/',import.meta.url);
await fs.mkdir(out,{recursive:true});const rng=seed=>()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);
function fixtures(){const f={};for(let declarer=0;declarer<4;declarer++){
 const random=rng(declarer+1),r={version:1,initial:{deck:E.shuffled(random),boards:4},actions:[]};let s=E.start(r.initial);const act=a=>{r.actions.push(a);s=E.step(s,a);};const snapshot=()=>structuredClone(r);
 while(s.turn!==declarer){if(s.turn===0)f.auction||=snapshot();act({type:'call',call:'pass'});}
 if(declarer===0){f.auction=snapshot();}act({type:'call',call:'bid',level:1,strain:declarer%2===0?'N':'H'});
 while(s.phase==='auction')act({type:'call',call:'pass'});f['opening'+declarer]=snapshot();
 while(s.phase==='play'||s.phase==='trick'){
  if(s.phase==='play'&&s.dummyOpen){f['exposed'+declarer]||=snapshot();if(E.humanTurn(s)&&s.turn===2)f.north||=snapshot();if(E.humanTurn(s)&&s.turn===0){f.south||=snapshot();if(E.legalCards(s.hands[0],s.trick).length<s.hands[0].length)f.follow||=snapshot();}}
  if(s.phase==='trick')f.trick||=snapshot();act(s.phase==='trick'?{type:'collect'}:E.chooseAction(E.viewFor(s,s.turn)));
 }f.boardOver||=snapshot();while(s.phase!=='sessionOver'){act(s.phase==='boardOver'?{type:'nextBoard',deck:E.shuffled(random)}:s.phase==='trick'?{type:'collect'}:E.chooseAction(E.viewFor(s,s.turn)));}f.sessionOver||=snapshot();
 }
 // South can double East's bid; redouble East's double of North.
 for(const mode of ['double','redouble']){const r={version:1,initial:{deck:E.shuffled(rng(8)),boards:4},actions:mode==='double'?[{type:'call',call:'pass'},{type:'call',call:'bid',level:1,strain:'S'}]:[{type:'call',call:'bid',level:1,strain:'S'},{type:'call',call:'double'}]};f[mode]=r;}
 f.passed={version:1,initial:{deck:E.shuffled(rng(2)),boards:4},actions:Array.from({length:4},()=>({type:'call',call:'pass'}))};return f;}
const F=fixtures();await fs.writeFile(new URL('fixtures.json',out),JSON.stringify(F));
async function setup(page){await page.addInitScript(key=>{if(!window.name.startsWith('bridge-fixture:'))return;const d=JSON.parse(window.name.slice(15));window.name='';localStorage.setItem(key,d.main);if(d.backup)localStorage.setItem(key+'-backup',d.backup);else localStorage.removeItem(key+'-backup');},KEY);}
async function seed(page,record,backup=null){await page.evaluate(d=>{window.name='bridge-fixture:'+JSON.stringify(d);},{main:typeof record==='string'?record:JSON.stringify(record),backup:backup?JSON.stringify(backup):null});await page.reload();}
const results=[],errors=[];
if(!process.env.TOUCH_ONLY){const browser=await webkit.launch();try{const p=await browser.newPage({viewport:{width:390,height:740},serviceWorkers:'block'});p.on('pageerror',e=>errors.push(e.message));await setup(p);await p.clock.install();await p.clock.pauseAt(new Date());await p.goto(url);const read=()=>p.evaluate(key=>JSON.parse(localStorage.getItem(key)),KEY);
const sizes=[[320,568],[375,667],[390,740],[430,932],[667,375],[844,390],[768,1024],[1024,768],[1366,768]];let count=0;
for(const [width,height] of sizes){await p.setViewportSize({width,height});for(const name of Object.keys(F)){await seed(p,F[name]);const g=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,cards:[...document.querySelectorAll('.hand .card')].map(c=>{const r=c.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,width:r.width,exposed:document.elementFromPoint(r.left+r.width/2,r.top+10)?.closest('button')===c};})}));assert.equal(g.overflow,false,`${name} overflow ${width}`);for(const c of g.cards){assert.ok(c.width>=35,`${name} width ${c.width}`);assert.ok(c.left>=0&&c.right<=width+1);if(c.top>=0&&c.top+10<height-75)assert.ok(c.exposed,`${name} card obscured ${width}`);}if(width===390&&['auction','north','exposed2','trick'].includes(name)||width===844&&name==='exposed1'||width===1366&&name==='exposed0')await p.screenshot({path:new URL(`${name}-${width}x${height}.png`,out).pathname,fullPage:true});count++;}}
results.push({check:'WebKit layouts and exposed card indices',passed:count,viewports:sizes});
if(process.env.LAYOUT_ONLY){await fs.writeFile(new URL('layout-results.json',out),JSON.stringify(results,null,2));console.log(results);process.exit(0);}
await p.setViewportSize({width:390,height:740});await seed(p,F.auction);await p.locator('#strain-S').click();await p.locator('#bid-up').click();assert.ok(await p.locator('#primary-action').isDisabled());await p.locator('#strain-H').click();await p.reload();assert.equal(await p.locator('#primary-action').innerText(),'Confirm 2♥');await p.locator('#call-pass').click();await p.locator('#primary-action').click();assert.equal(E.restore(await read()).auction.at(-1).call,'pass');
for(const kind of ['double','redouble']){await seed(p,F[kind]);await p.locator('#call-'+kind).click();await p.locator('#primary-action').click();assert.equal(E.restore(await read()).contract.double,kind==='double'?2:4);}
for(const name of ['north','south']){await seed(p,F[name]);const s=E.restore(await read()),cards=p.locator('.hand .card:not(:disabled)');assert.equal(await cards.first().getAttribute('data-player'),String(s.turn));await cards.first().click({position:{x:12,y:12}});const first=await p.locator('.card[aria-pressed=true]').getAttribute('data-card');await p.reload();assert.equal(await p.locator('.card[aria-pressed=true]').getAttribute('data-card'),first);if(await cards.count()>1){await cards.nth(1).click({position:{x:12,y:12}});assert.notEqual(await p.locator('.card[aria-pressed=true]').getAttribute('data-card'),first);}await p.setViewportSize({width:844,height:390});await p.locator('#primary-action').click();assert.equal(E.restore(await read()).hands[s.turn].length,s.hands[s.turn].length-1);await p.setViewportSize({width:390,height:740});}
results.push({check:'auction correction and reload, double/redouble, both human hands, card correction and rotation',passed:true});
await seed(p,F.opening2);assert.equal(await p.locator('#exposed-zone').isVisible(),false);await p.clock.runFor(1500);assert.equal(await p.locator('#exposed-zone').isVisible(),true);assert.match(await p.locator('#exposed-label').innerText(),/Declarer hand/);
await p.locator('#menu-button').click();const paused=JSON.stringify(await read());await p.clock.runFor(10000);assert.equal(JSON.stringify(await read()),paused);for(const kind of ['help','auction','scores','settings','new']){if(kind!=='help'){await p.locator('#close-panel').click();await p.locator('#menu-button').click();}await p.locator(`[data-panel=${kind}]`).click();assert.ok(await p.locator('#close-panel').isVisible());}await p.locator('#keep-playing').click();assert.equal(await p.locator(':focus').getAttribute('id'),'menu-button');
await p.locator('#menu-button').click();await p.locator('[data-panel=settings]').click();await p.locator('#boards').selectOption('8');await p.locator('#pace').selectOption('steady');await p.locator('#save-settings').click();assert.equal(E.restore(await read()).total,4);
await seed(p,F.auction);await p.locator('#strain-S').focus();await p.keyboard.press('Space');assert.equal(await p.locator(':focus').getAttribute('id'),'strain-S');await p.locator('#primary-action').focus();await p.keyboard.press('Enter');assert.equal(E.restore(await read()).contract.strain,'S');assert.equal(await p.locator(':focus').getAttribute('id'),'instruction');await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.card').first().evaluate(c=>getComputedStyle(c).transitionDuration),'0s');
results.push({check:'opening lead reveal, menus pause, focus, settings, keyboard and reduced motion',passed:true});
await seed(p,F.auction);let moves=0;while(true){await p.clock.runFor(600);const s=E.restore(await read());if(s.phase==='sessionOver')break;assert.ok(++moves<900);if(['trick','boardOver'].includes(s.phase)){await p.locator('#primary-action').click();continue;}if(!E.humanTurn(s)){await p.clock.runFor(1500);continue;}const a=E.chooseAction(E.viewFor(s,s.turn));if(a.type==='call'){if(a.call==='bid'){let level=Number((await p.locator('#bid-value').innerText()).match(/Level (\d)/)[1]);while(level<a.level){await p.locator('#bid-up').click();level++;}while(level>a.level){await p.locator('#bid-down').click();level--;}await p.locator('#strain-'+a.strain).click();}else await p.locator('#call-'+a.call).click();}else await p.locator(`[data-card="${a.card}"]:not(:disabled)`).click({position:{x:12,y:12}});await p.locator('#primary-action').click();}
await p.reload();assert.equal(E.restore(await read()).phase,'sessionOver');await p.locator('#primary-action').click();assert.equal(E.restore(await read()).total,8);results.push({check:'complete four-board session through UI and timers, final reload, new-session settings',iterations:moves,passed:true});
await seed(p,'{broken',F.north);assert.match(await p.locator('#storage-note').innerText(),/Recovered/);await seed(p,{...F.follow,selection:{card:'BAD',call:{call:'bad'},level:99}});assert.ok(await p.locator('#primary-action').isDisabled());
// Repeated actions must never accept a changed button meaning.
await seed(p,F.trick);const n=(await read()).actions.length;await p.locator('#primary-action').dblclick();assert.equal((await read()).actions.length,n+1);await p.locator('#primary-action').dispatchEvent('keydown',{key:'Enter',repeat:true});assert.equal((await read()).actions.length,n+1);
const denied=await browser.newContext();await denied.addInitScript(()=>{Storage.prototype.setItem=()=>{throw Error('storage blocked');};});const dp=await denied.newPage();await dp.goto(url);assert.match(await dp.locator('#storage-note').innerText(),/cannot save/);await denied.close();assert.deepEqual(errors,[]);results.push({check:'recovery, malformed selection, duplicate activation and denied storage',passed:true});
}finally{await browser.close();}}
const chrome=await chromium.launch({channel:'chrome'});try{const context=await chrome.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'block'}),p=await context.newPage();await setup(p);await p.clock.install();await p.clock.pauseAt(new Date());await p.goto(url);const cdp=await context.newCDPSession(p),read=()=>p.evaluate(key=>JSON.parse(localStorage.getItem(key)),KEY);
async function touch(selector,{hold=60,drift=0,cancel=false,extra=false}={}){const el=p.locator(selector).first();await el.scrollIntoViewIfNeeded();const r=await el.boundingBox(),x=r.x+r.width/2,y=r.y+12;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await new Promise(r=>setTimeout(r,hold));if(extra)await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1},{x:x+20,y:y+40,id:2}]});if(drift)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y-drift,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:cancel?'touchCancel':'touchEnd',touchPoints:[]});}
await seed(p,F.auction);await touch('#bid-up',{hold:6500,drift:24});assert.match(await p.locator('#bid-value').innerText(),/Level 2/);await touch('#strain-S');let n=(await read()).actions.length;await touch('#primary-action',{hold:6500,drift:24});assert.equal((await read()).actions.length,n+1);
for(const name of ['north','south']){await seed(p,F[name]);await touch('.card:not(:disabled)',{drift:20});assert.equal(await p.locator('.card[aria-pressed=true]').count(),0);await touch('.card:not(:disabled)',{hold:6500});assert.equal(await p.locator('.card[aria-pressed=true]').count(),1);n=(await read()).actions.length;for(const opts of [{drift:70},{cancel:true},{extra:true}]){await touch('#primary-action',opts);assert.equal((await read()).actions.length,n);}await touch('#primary-action',{drift:24});assert.equal((await read()).actions.length,n+1);}
await seed(p,F.north);await touch('.card:not(:disabled)');n=(await read()).actions.length;await touch('#menu-button',{drift:24});await touch('#close-panel',{drift:24});assert.equal((await read()).actions.length,n);assert.equal(await p.evaluate(()=>getSelection().toString()),'');await context.close();results.push({check:'native Chromium touch: 6.5-second holds, 24px button drift, tight card drift for both hands, large drag/cancel/extra finger/modal duplicate suppression',passed:true});
const oc=await chrome.newContext(),op=await oc.newPage();await op.goto(url);await op.evaluate(()=>navigator.serviceWorker.ready);await op.reload();const count=await op.evaluate(async()=>{const c=await caches.open('ai-bridge-v1');return(await c.keys()).length;});assert.equal(count,12);await oc.setOffline(true);await op.reload();await op.locator('#menu-button').click();await op.locator('[data-panel=help]').click();assert.match(await op.locator('#panel-body').innerText(),/Declarer and dummy/);results.push({check:'offline reload and help, 12 cached runtime/install assets',passed:true});await oc.close();
}finally{await chrome.close();}
await fs.writeFile(new URL(process.env.TOUCH_ONLY?'touch-results.json':'results.json',out),JSON.stringify({checkedAt:new Date().toISOString(),results,errors},null,2));console.log(JSON.stringify(results,null,2));
