const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../engine.js');
const rng=seed=>()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);
const initial=()=>({deck:E.shuffled(rng(1)),boards:4});
const call=(s,call,level,strain)=>E.step(s,{type:'call',call,level,strain});
function contract(level=1,strain='N',double=1){return {level,strain,double};}
test('52 unique cards, clockwise dealing, standard board vulnerability and dealer',()=>{const s=E.start(initial());assert.equal(new Set(s.hands.flat()).size,52);assert.ok(s.hands.every(h=>h.length===13));assert.equal(s.dealer,2);assert.deepEqual(E.vulnerability(1),[false,false]);assert.deepEqual(E.vulnerability(2),[true,false]);assert.deepEqual(E.vulnerability(3),[false,true]);assert.deepEqual(E.vulnerability(4),[true,true]);assert.deepEqual(E.vulnerability(17),E.vulnerability(1));assert.throws(()=>E.start({deck:Array(52).fill('AS')}));});
test('auction ranks, doubles through passes, redoubles and new bid reset',()=>{let s=E.start(initial());s=call(s,'bid',1,'H');assert.throws(()=>call(s,'bid',1,'D'));s=call(s,'double');s=call(s,'pass');s=call(s,'pass');assert.ok(E.legalCalls(s).some(a=>a.call==='redouble'));s=call(s,'redouble');assert.equal(s.contract.double,4);s=call(s,'bid',1,'S');assert.equal(s.contract.double,1);s=call(s,'pass');assert.throws(()=>call(s,'double'));s=call(s,'pass');assert.ok(E.legalCalls(s).some(a=>a.call==='double'));});
test('four initial passes score zero and advance, three after bid declare first strain bidder',()=>{let s=E.start(initial());for(let i=0;i<4;i++)s=call(s,'pass');assert.equal(s.phase,'boardOver');assert.equal(s.result.ns,0);s=E.step(s,{type:'nextBoard',deck:E.deck()});assert.equal(s.dealer,3);assert.equal(s.board,2);let d=E.start(initial());d=call(d,'bid',1,'H');d=call(d,'pass');d=call(d,'bid',2,'H');for(let i=0;i<3;i++)d=call(d,'pass');assert.equal(d.contract.declarer,2);assert.equal(d.contract.dummy,0);assert.equal(d.turn,3);assert.equal(d.dummyOpen,false);d=E.step(d,E.chooseAction(E.viewFor(d,d.turn)));assert.equal(d.dummyOpen,true);assert.equal(d.turn,0);assert.equal(E.humanTurn(d),true);});
test('follow suit, trump beats lead, no-trump and unrestricted trump leads',()=>{assert.deepEqual(E.legalCards(['AS','2H','3S'],[{player:1,card:'2S'}]),['AS','3S']);assert.deepEqual(E.legalCards(['2H'],[{player:1,card:'2S'}]),['2H']);const t=[{player:0,card:'AS'},{player:1,card:'2H'},{player:2,card:'KS'},{player:3,card:'AC'}];assert.equal(E.winningPlay(t,'H').player,1);assert.equal(E.winningPlay(t,'N').player,0);assert.equal(E.legalCards(['AS','2H'],[]).length,2);});
test('duplicate contract scores from independent known examples',()=>{for(const [l,s,m,t,v,points] of [[4,'S',1,10,false,420],[4,'S',1,10,true,620],[3,'N',1,9,false,400],[3,'N',1,9,true,600],[2,'H',1,9,false,140],[5,'C',1,11,true,600],[2,'H',2,8,false,470],[1,'N',4,7,false,560],[6,'N',1,12,false,990],[6,'N',1,12,true,1440],[7,'S',1,13,false,1510],[7,'N',1,13,true,2220],[2,'S',2,9,false,570],[2,'S',4,9,true,1240],[4,'S',1,8,false,-100],[4,'S',1,8,true,-200],[4,'S',2,6,false,-800],[4,'S',2,6,true,-1100],[4,'S',4,6,false,-1600]])assert.equal(E.scoreContract(contract(l,s,m),t,v).points,points,[l,s,m,t,v].join('/'));});
test('computer view hides other hands and dummy until opening lead',()=>{let s=E.start(initial());let v=E.viewFor(s,2);assert.equal(v.hands,undefined);assert.equal(v.dummy,null);s=call(s,'bid',1,'N');for(let i=0;i<3;i++)s=call(s,'pass');assert.equal(E.viewFor(s,s.turn).dummy,null);assert.deepEqual(E.viewFor(s,s.contract.dummy).ownHand,s.hands[s.contract.dummy]);s=E.step(s,E.chooseAction(E.viewFor(s,s.turn)));v=E.viewFor(s,0);assert.equal(v.dummy.player,0);assert.deepEqual(v.ownHand,s.hands[2]);const w=E.viewFor(s,1);assert.deepEqual(w.ownHand,s.hands[1]);assert.equal(w.ownHand.includes(s.hands[2][0]),false);});
test('save replay rejects illegal moves, corrupt decks, impossible ordering and oversized logs',()=>{const i=initial(),s=E.start(i);assert.deepEqual(E.restore({version:1,initial:i,actions:[]}),s);assert.throws(()=>E.restore({version:1,initial:i,actions:[{type:'play',card:'AS'}]}));assert.throws(()=>E.restore({version:1,initial:i,actions:Array(5001).fill({type:'collect'})}));assert.throws(()=>E.step(s,{type:'nextBoard',deck:E.deck()}));});
test('200 full four-board sessions conserve cards, terminate, score once and replay',()=>{let passed=0;for(let seed=1;seed<=200;seed++){const random=rng(seed),i={deck:E.shuffled(random),boards:4},r={version:1,initial:i,actions:[]};let s=E.start(i),n=0;while(s.phase!=='sessionOver'){assert.ok(++n<600);const all=s.hands.flat().concat(s.trick.map(p=>p.card),s.completed.flatMap(t=>t.plays.map(p=>p.card)));assert.equal(all.length,52);assert.equal(new Set(all).size,52);const a=s.phase==='trick'?{type:'collect'}:s.phase==='boardOver'?{type:'nextBoard',deck:E.shuffled(random)}:E.chooseAction(E.viewFor(s,s.turn));r.actions.push(a);s=E.step(s,a);}assert.equal(s.history.length,4);assert.equal(s.net,s.history.reduce((n,r)=>n+r.ns,0));assert.deepEqual(E.restore(r),s);passed+=s.history.filter(r=>r.passed).length;assert.throws(()=>E.step(s,{type:'collect'}));}console.log('800 complete boards; passed-out boards:',passed);});
