const test=require('node:test'),assert=require('node:assert/strict'),E=require('../engine.js');
const rng=seed=>()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);
function inventory(s){return [...s.stock,...s.discard,...s.hands.flat(),...s.melds.flatMap(m=>m.cards)];}
function position(hand,extras={}){const s=E.start();s.turn=0;s.phase='play';s.hands[0]=hand;s.melds=[];Object.assign(s,extras);return s;}
test('52 unique cards, 10 per hand, alternating deal and initial turn',()=>{const s=E.start({dealer:1});assert.equal(new Set(inventory(s)).size,52);assert.deepEqual(s.hands.map(h=>h.length),[10,10]);assert.equal(s.stock.length,31);assert.equal(s.turn,0);s.phase='handOver';const n=E.step(s,{type:'nextHand',deck:E.shuffled()});assert.equal(n.turn,1);assert.equal(n.handNumber,2);});
test('sets, runs, ace boundaries, gaps and duplicate rejection',()=>{assert.equal(E.meldKind(['C7','H7','D7']),'set');assert.equal(E.meldKind(['C7','H7','D7','S7']),'set');assert.equal(E.meldKind(['H1','H2','H3']),'run');assert.equal(E.meldKind(['H11','H12','H13']),'run');for(const ids of [['H12','H13','H1'],['H13','H1','H2'],['C7','C7','D7'],['H2','H4','H5'],['C2','D3','S4']])assert.equal(E.meldKind(ids),null);});
test('must draw exactly once, illegal moves leave source state unchanged',()=>{const s=E.start(),before=JSON.stringify(s);assert.throws(()=>E.step(s,{type:'discard',card:s.hands[0][0]}));assert.equal(JSON.stringify(s),before);const p=E.step(s,{type:'draw',source:'stock'});assert.equal(p.hands[0].length,11);assert.throws(()=>E.step(p,{type:'draw',source:'stock'}));});
test('discard pickup cannot be discarded or stranded as sole card',()=>{let s=position(['C2','D2','H2','S9'],{takenDiscard:'S9'});assert.throws(()=>E.step(s,{type:'discard',card:'S9'}));assert.throws(()=>E.step(s,{type:'meld',cards:['C2','D2','H2']}),/Keep another/);const a=E.chooseAction(E.viewFor(s));assert.equal(a.type,'discard');assert.notEqual(a.card,'S9');});
test('layoff to either player, multiple additions, no rearranging',()=>{const s=position(['H3','H7','C8'],{melds:[{owner:1,kind:'run',cards:['H4','H5','H6']}]});const n=E.step(s,{type:'add',cards:['H3','H7'],meld:0});assert.deepEqual(n.melds[0].cards,['H3','H4','H5','H6','H7']);assert.deepEqual(n.hands[0],['C8']);assert.throws(()=>E.step(s,{type:'add',cards:['C8'],meld:0}));});
test('go out by meld, layoff or discard; hand values and target',()=>{for(const [hand,melds,a] of [[['H1','H2','H3'],[],{type:'meld',cards:['H1','H2','H3']}],[['D7'],[{kind:'set',cards:['C7','H7','S7'],owner:1}],{type:'add',cards:['D7'],meld:0}],[['C1'],[],{type:'discard',card:'C1'}]]){const s=position(hand,{melds,hands:[hand,['S1','S11','D5']],score:[84,0]});const n=E.step(s,a);assert.equal(n.phase,'matchOver');assert.equal(n.result.earned,16);assert.deepEqual(n.score,[100,0]);assert.throws(()=>E.step(n,a));}});
test('recycle leaves top discard, reverses stock, ends after two recycles',()=>{const s=position(['C1'],{phase:'draw',stock:[],discard:['H1','H2','H3'],recycles:0});const n=E.step(s,{type:'draw',source:'stock'});assert.equal(n.hands[0].at(-1),'H1');assert.deepEqual(n.discard,['H3']);assert.deepEqual(n.stock,['H2']);assert.equal(n.recycles,1);s.recycles=2;assert.throws(()=>E.step(s,{type:'draw',source:'stock'}));assert.ok(E.step(s,{type:'endBlocked'}).result);});
test('blocked hand scores difference, ties zero, no-progress cap',()=>{let s=position(['H2'],{phase:'draw',stock:[],recycles:2,hands:[['H2'],['C12']]});let n=E.step(s,{type:'endBlocked'});assert.equal(n.result.winner,0);assert.equal(n.result.earned,8);s.hands[1]=['C2'];n=E.step(s,{type:'endBlocked'});assert.equal(n.result.winner,null);assert.equal(n.result.earned,0);s.phase='play';s.idle=39;s.hands[0]=['H2','H4'];n=E.step(s,{type:'discard',card:'H4'});assert.equal(n.phase,'handOver');assert.match(n.result.reason,/40 turns/);});
test('save replay rejects malformed and illegal records',()=>{const r={version:1,initial:{deck:E.shuffled(rng(3)),dealer:1,target:100},actions:[]};let s=E.start(r.initial);for(let i=0;i<20;i++){const a=E.chooseAction(E.viewFor(s));r.actions.push(a);s=E.step(s,a);}assert.deepEqual(E.restore(r),s);assert.throws(()=>E.restore({...r,version:7}));assert.throws(()=>E.restore({...r,initial:{}}));assert.throws(()=>E.restore({...r,actions:[{type:'discard',card:'C1'}]}));assert.throws(()=>E.start({deck:Array(52).fill('C1')}));});
test('bot observation excludes hidden hands and stock order',()=>{const s=E.start(),v=E.viewFor(s);assert.ok(!('hands'in v));assert.ok(!('stock'in v));const n=structuredClone(s);n.hands[1].reverse();n.stock.reverse();assert.deepEqual(E.chooseAction(E.viewFor(n)),E.chooseAction(v));});
test('200 deterministic full matches maintain card conservation, legality and scores',()=>{for(let seed=1;seed<=200;seed++){const random=rng(seed);let s=E.start({deck:E.shuffled(random),dealer:seed%2}),moves=0;while(s.phase!=='matchOver'){assert.ok(++moves<15000,`seed ${seed}`);const a=s.phase==='handOver'?{type:'nextHand',deck:E.shuffled(random)}:E.chooseAction(E.viewFor(s));s=E.step(s,a);assert.equal(inventory(s).length,52);assert.equal(new Set(inventory(s)).size,52);for(const m of s.melds)assert.equal(E.meldKind(m.cards),m.kind);assert.ok(s.score.every(n=>n>=0));}assert.ok(s.score[s.winner]>=s.target);}});

test('a turn with a table play is not counted as an idle turn',()=>{let s=position(['H2','D2','S2','C4','C5'],{idle:39});s=E.step(s,{type:'meld',cards:['H2','D2','S2']});s=E.step(s,{type:'discard',card:'C4'});assert.equal(s.idle,0);assert.equal(s.phase,'draw');});
