'use strict';
(() => {
  const E=Rummy,KEY='ai-rummy-game-v1',SETTINGS='ai-rummy-settings-v1',$=id=>document.getElementById(id),panel=$('panel');
  const names=['You','Computer'],suits={C:'Clubs',D:'Diamonds',S:'Spades',H:'Hearts'},symbols={C:'♣',D:'♦',S:'♠',H:'♥'},ranks={A:'Ace',J:'Jack',Q:'Queen',K:'King'};
  const cardName=id=>{const c=E.card(id);return `${ranks[c.rank]||c.rank} of ${suits[c.suit]}`;};
  const short=id=>{const c=E.card(id);return c.rank+symbols[c.suit];};
  const face=id=>{const c=E.card(id);return cardSVG(c.rank,c.suit);};
  const tokens=ids=>ids.map(id=>`<span class="token ${'HD'.includes(E.card(id).suit)?'red':''}" aria-label="${cardName(id)}">${short(id)}</span>`).join('');
  let settings={target:100,pace:'relaxed',sort:'suit'},record,state,lastSaved=null,selection={cards:[],pile:null,meld:null},timer,generation=0,opener,dialogKind='',message='',warning='',offlineReady=false,actionUntil=0;
  const held=new Set();
  try{const x=JSON.parse(localStorage.getItem(SETTINGS));if(x)settings={target:x.target===200?200:100,pace:x.pace==='steady'?'steady':'relaxed',sort:x.sort==='rank'?'rank':'suit'};}catch{}
  function newMatch(renderNow=true){record={version:1,initial:{deck:E.shuffled(),dealer:Math.random()<.5?0:1,target:settings.target},actions:[]};state=E.start(record.initial);selection={cards:[],pile:null,meld:null};message='';save();if(renderNow)render();}
  function load(){let damaged=false;for(const key of [KEY,KEY+'-backup'])try{const raw=localStorage.getItem(key);if(!raw)continue;const data=JSON.parse(raw);state=E.restore(data);record=data;lastSaved=raw;if(data.selection&&typeof data.selection==='object')selection={cards:Array.isArray(data.selection.cards)?[...new Set(data.selection.cards.filter(id=>state.hands[0].includes(id)))]:[],pile:['stock','discard'].includes(data.selection.pile)?data.selection.pile:null,meld:Number.isInteger(data.selection.meld)&&state.melds[data.selection.meld]?data.selection.meld:null};if(key!==KEY)warning='Recovered the previous saved position.';return;}catch{damaged=true;}if(damaged)warning='The saved match could not be read. A new match is ready.';newMatch(false);}
  function save(){record.selection=structuredClone(selection);try{const raw=JSON.stringify(record);if(lastSaved)localStorage.setItem(KEY+'-backup',lastSaved);localStorage.setItem(KEY,raw);lastSaved=raw;}catch{warning='This browser cannot save progress. Keep this tab open to finish your match.';}}
  function commit(a){try{state=E.step(state,a);record.actions.push(a);selection={cards:[],pile:null,meld:null};message='';save();render();}catch(e){message=e.message;render();}}
  function human(){return state.turn===0&&['draw','play'].includes(state.phase);}
  function schedule(){clearTimeout(timer);if(!['draw','play'].includes(state.phase)||state.turn===0||panel.open||document.hidden||held.size)return;const stamp=generation;timer=setTimeout(()=>{if(stamp===generation&&!panel.open&&!document.hidden&&!held.size)commit(E.chooseAction(E.viewFor(state,1)));},settings.pace==='steady'?700:1300);}
  function render(){
    generation++;const active=human(),play=active&&state.phase==='play',draw=active&&state.phase==='draw';
    selection.cards=selection.cards.filter(id=>state.hands[0].includes(id));
    const focus=document.activeElement,focusId=focus?.id,focusCard=focus?.dataset?.card,focusMeld=focus?.dataset?.meld;
    $('you-score').textContent=state.score[0];$('computer-score').textContent=state.score[1];$('target-score').textContent=state.target;$('hand-number').textContent=`Hand ${state.handNumber}`;
    $('opponent-count').textContent=`Computer · ${state.hands[1].length} ${state.hands[1].length===1?'card':'cards'}`;$('hand-count').textContent=`· ${state.hands[0].length} cards`;$('stock-count').textContent=state.stock.length?`${state.stock.length} cards`:E.stockAvailable(state)?'Recycle ready':'Empty';
    const top=state.discard.at(-1);$('discard-face').innerHTML=top?face(top):'';$('discard-label').textContent=top?short(top):'Empty';$('discard').setAttribute('aria-label',top?`Discard: ${cardName(top)}`:'Discard pile empty');
    $('stock').disabled=!draw;$('discard').disabled=!draw||!top;$('stock').setAttribute('aria-pressed',String(selection.pile==='stock'));$('discard').setAttribute('aria-pressed',String(selection.pile==='discard'));
    $('stock').setAttribute('aria-label',E.stockAvailable(state)?`Stock: ${state.stock.length?state.stock.length+' cards':'recycle discard pile'}`:'Stock exhausted: select to end this hand');
    $('table-note').innerHTML=state.phase==='draw'&&active?'Draw one.<br>Make your move.':state.turn===1&&['play','draw'].includes(state.phase)?'Computer’s<br>turn.':'Build sets.<br>Follow runs.';
    $('hand').innerHTML=E.sorted(state.hands[0],settings.sort).map(id=>`<button class="card${id===state.takenDiscard&&play?' kept':''}" data-card="${id}" aria-label="${cardName(id)}${id===state.takenDiscard&&play?', cannot discard this turn':''}" aria-pressed="${selection.cards.includes(id)}" ${!play?'disabled':''}>${face(id)}</button>`).join('');
    $('meld-count').textContent=state.melds.length?`${state.melds.length} ${state.melds.length===1?'meld':'melds'}`:'Sets & runs';
    const scroll=$('melds').scrollTop;
    $('melds').innerHTML=state.melds.length?state.melds.map((m,i)=>`<button class="meld${play&&E.canAdd(m,selection.cards)?' compatible':''}" data-meld="${i}" aria-pressed="${selection.meld===i}" aria-label="${names[m.owner]}'s ${m.kind}: ${m.cards.map(cardName).join(', ')}${play&&E.canAdd(m,selection.cards)?'; selected cards can be added':''}" ${!play?'disabled':''}><span class="owner">${names[m.owner]}<br>${m.kind==='set'?'Set':'Run'}</span><span class="tokens">${tokens(m.cards)}</span></button>`).join(''):'<p class="empty-table">Sets and runs stay here.<br>Either player can add to them.</p>';$('melds').scrollTop=scroll;
    $('sort').textContent=`Sort: ${settings.sort} ↕`;$('last-turn').disabled=!state.last.length;$('hint').disabled=!active;$('play-actions').hidden=!play;$('clear').hidden=!(selection.cards.length||selection.pile||selection.meld!==null);
    $('meld-action').disabled=!play||!E.meldKind(selection.cards);$('add-action').disabled=!play||selection.meld===null||!E.canAdd(state.melds[selection.meld],selection.cards);
    $('add-action').textContent=selection.meld===null?'Add to table':`Add to ${state.melds[selection.meld]?.kind||'table'}`;
    const primary=$('primary-action');primary.disabled=false;let status,detail;
    if(draw){status='Your turn · draw';detail=selection.pile==='discard'?`Take ${cardName(top)}. You must keep it until a later turn.`:selection.pile==='stock'?E.stockAvailable(state)?'Draw one face-down card. Then lay cards or discard.':'The stock is exhausted. The lower hand value scores the difference.':'Choose the stock or the top discard, then confirm.';primary.textContent=selection.pile==='stock'?E.stockAvailable(state)?'Draw from stock':'End blocked hand':selection.pile==='discard'?`Take ${short(top)}`:'Choose a pile';primary.disabled=!selection.pile;}
    else if(play){status='Your turn · play';detail=selection.cards.length?selection.cards.map(short).join(' · ')+(selection.meld!==null?` → table ${state.melds[selection.meld].kind}`:selection.cards.length===1?' · Discard, or select a table meld to extend.':' · Lay a set or run, or select a table meld.'): 'Choose cards to lay down, or one card to discard.';primary.textContent=selection.cards.length===1?`Discard ${short(selection.cards[0])}`:'Select one card to discard';primary.disabled=selection.cards.length!==1||selection.cards[0]===state.takenDiscard;if(selection.cards.length===1&&selection.cards[0]===state.takenDiscard)detail='Keep the card you took from the discard this turn. You can still lay it on the table.';}
    else if(['handOver','matchOver'].includes(state.phase)){const r=state.result;status=state.phase==='matchOver'?(state.winner===0?'You win the match!':'Computer wins the match'):r.winner===null?'A tied hand':r.winner===0?'You win the hand!':'Computer wins the hand';detail=`${r.reason}. ${r.winner===null?'No points this hand.':`${names[r.winner]} ${r.winner===0?'score':'scores'} ${r.earned} points.`}`;primary.textContent=state.phase==='matchOver'?'Play again':'Deal next hand';}
    else{status='Computer is playing…';detail=state.turnLog.at(-1)?friendly(state.turnLog.at(-1)):'Your turn follows the computer’s discard.';primary.textContent='Computer’s turn';primary.disabled=true;}
    $('status').textContent=status;$('detail').textContent=message||detail;
    $('result').hidden=!state.result;$('result').innerHTML=state.result?`<p>Cards left: You ${state.result.values[0]} points · Computer ${state.result.values[1]} points.</p><strong>Computer’s remaining cards</strong><div class="result-hand">${tokens(E.sorted(state.hands[1]))||'None'}</div>`:'';
    $('storage-note').textContent=warning;$('save-status').textContent=offlineReady?'Saved here · Offline ready':'Progress saves here';
    if(!panel.open){const target=focusCard?document.querySelector(`[data-card="${focusCard}"]`):focusMeld?document.querySelector(`[data-meld="${focusMeld}"]`):focusId?$(focusId):null;if(target&&!target.disabled)target.focus({preventScroll:true});}
    schedule();
  }
  function friendly(text){return text.replace(/\b[CDSH](?:1[0-3]|[1-9])\b/g,short);}
  function selectPile(pile){if(!human()||state.phase!=='draw')return;selection.pile=selection.pile===pile?null:pile;message='';save();render();}
  $('stock').onclick=()=>selectPile('stock');$('discard').onclick=()=>selectPile('discard');
  $('hand').onclick=event=>{const b=event.target.closest('[data-card]');if(!b||b.disabled)return;const id=b.dataset.card;selection.cards=selection.cards.includes(id)?selection.cards.filter(c=>c!==id):[...selection.cards,id];message='';save();render();};
  $('melds').onclick=event=>{const b=event.target.closest('[data-meld]');if(!b||b.disabled)return;const i=Number(b.dataset.meld);selection.meld=selection.meld===i?null:i;message='';save();render();};
  $('clear').onclick=()=>{selection={cards:[],pile:null,meld:null};message='';save();render();};
  $('sort').onclick=()=>{settings.sort=settings.sort==='suit'?'rank':'suit';try{localStorage.setItem(SETTINGS,JSON.stringify(settings));}catch{}render();};
  $('hint').onclick=()=>{if(!human())return;const a=E.chooseAction(E.viewFor(state,0));selection={cards:a.cards|| (a.card?[a.card]:[]),pile:a.source|| (a.type==='endBlocked'?'stock':null),meld:a.meld??null};message=a.type==='meld'?'These cards make a set or run. Press Lay set / run to play them.':a.type==='add'?'This card extends the selected table meld. Press Add to confirm.':a.type==='discard'?`Consider discarding ${cardName(a.card)}. You can change this selection.`:a.type==='endBlocked'?'The stock is exhausted. End the hand, or choose the discard instead.':'Suggested draw selected. Confirm it, or choose the other pile.';save();render();};
  function guarded(fn){return event=>{if(event.detail>1||performance.now()<actionUntil)return;actionUntil=performance.now()+500;fn();};}
  $('primary-action').onclick=guarded(()=>{if(panel.open)return;if(state.phase==='handOver')commit({type:'nextHand',deck:E.shuffled()});else if(state.phase==='matchOver')newMatch();else if(human()&&state.phase==='draw'&&selection.pile)commit(selection.pile==='stock'&&!E.stockAvailable(state)?{type:'endBlocked'}:{type:'draw',source:selection.pile});else if(human()&&state.phase==='play'&&selection.cards.length===1)commit({type:'discard',card:selection.cards[0]});});
  $('meld-action').onclick=guarded(()=>{if(human())commit({type:'meld',cards:selection.cards});});$('add-action').onclick=guarded(()=>{if(human())commit({type:'add',cards:selection.cards,meld:selection.meld});});
  document.addEventListener('keydown',e=>{if(e.repeat&&['Enter',' '].includes(e.key)&&e.target.matches('button'))e.preventDefault();});
  const help=`<div class="help-text"><h3>Draw. Build. Discard.</h3><p>You play against the computer with ten cards each. Be first to empty your hand. The winner earns the value of the other player’s remaining cards. First to the match target wins.</p><h3>1. Draw one card</h3><p>Select the face-down stock or the top discard, then confirm with the gold button. You can change your choice first. A card taken from the discard cannot be discarded again on the same turn.</p><h3>2. Lay cards on the table</h3><p>A set is three or four cards of one rank, such as 7♣ 7♦ 7♥. A run is three or more consecutive cards of one suit, such as 4♥ 5♥ 6♥. Aces are low: A-2-3 works; Q-K-A does not.</p><p>Select all the cards, then press Lay set / run. To add cards to an existing meld, select your cards, select the set or run on the table, and press Add. Either player can extend any meld. You cannot rearrange cards already on the table. Tap a selected card again to remove it from your choice.</p><h3>3. Discard to end your turn</h3><p>Select one card and press Discard. Laying cards is optional. You may lay several sets or runs in one turn, then discard. You may also go out by laying your last card; no final discard is required.</p><h3>Scoring and house rules</h3><p>Aces count 1, number cards their number, and J/Q/K 10. All cards left in the losing hand count, even possible sets or runs. There is no bonus for going out all at once. The default target is 100; Settings offers 200 for your next match. A random dealer starts the match; the non-dealer plays first and the deal alternates.</p><p>When the stock is empty, you can take the discard or recycle. The top discard stays; the rest turns over without shuffling. This can happen twice. After that, select the empty stock and confirm End blocked hand, or take the discard. A hand also ends after 40 consecutive turns without laying or adding cards. The lower remaining hand value scores the difference; a tie scores zero. This limit prevents endless exchanges.</p><h3>A quiet pace</h3><p>Hint suggests a move without playing it. Sort rearranges your view. Menu pauses computer play. Last turn records the previous player’s actions. Settings offers two computer speeds. The computer uses its own cards and the public table only; it is a casual opponent.</p><h3>Save and play offline</h3><p>Moves and selections save in this browser. An earlier save is retained for recovery. Load online once and wait for “Offline ready.” In Safari, use Share → Add to Home Screen. Clearing website data removes progress. No accounts, ads, analytics or paid features.</p><p>Rules references: <a href="https://www.pagat.com/rummy/rummy.html" target="_blank" rel="noopener">Pagat: Basic Rummy</a> and <a href="https://bicyclecards.com/how-to-play/rummy-rum" target="_blank" rel="noopener">Bicycle: Rummy</a>. The house rules above define this version.</p></div>`;
  function openPanel(kind,trigger){if(!panel.open)opener=trigger||document.activeElement;clearTimeout(timer);generation++;dialogKind=kind;const body=$('panel-body');
    if(kind==='menu'){$('panel-title').textContent='At the table';body.innerHTML='<div class="menu-list"><button data-panel="help">How to play <span>›</span></button><button data-panel="settings">Settings <span>›</span></button><button data-panel="last">Last turn <span>›</span></button><button data-panel="new">New match <span>›</span></button></div><p>Your match is paused here.</p>';}
    else if(kind==='help'){$('panel-title').textContent='How to play';body.innerHTML=help;}
    else if(kind==='settings'){$('panel-title').textContent='Settings';body.innerHTML='<label class="setting"><span>Computer pace</span><select id="pace"><option value="relaxed">Relaxed</option><option value="steady">Steady</option></select><small>Menu always pauses play.</small></label><label class="setting"><span>Match target</span><select id="target"><option value="100">100 points</option><option value="200">200 points</option></select><small>Applies to the next match.</small></label><button id="save-settings" class="primary">Save settings</button>';$('pace').value=settings.pace;$('target').value=String(settings.target);}
    else if(kind==='new'){$('panel-title').textContent='Start a new match?';body.innerHTML='<p>This replaces your saved match and resets both scores.</p><button id="new-match" class="primary">Start new match</button><button id="keep-playing" class="primary quiet">Keep playing</button>';}
    else if(kind==='last'){$('panel-title').textContent='Last turn';body.innerHTML=state.last.length?`<ul class="turn-log">${state.last.map(t=>`<li>${friendly(t)}</li>`).join('')}</ul>`:'<p>No completed turn yet.</p>';}
    body.scrollTop=0;if(!panel.open)panel.showModal();$('close-panel').focus({preventScroll:true});
  }
  function closed(){if(!dialogKind)return;dialogKind='';generation++;render();if(opener?.isConnected&&!opener.disabled)opener.focus({preventScroll:true});else $('menu-button').focus({preventScroll:true});}
  $('menu-button').onclick=()=>openPanel('menu',$('menu-button'));$('last-turn').onclick=()=>openPanel('last',$('last-turn'));$('close-panel').onclick=()=>panel.close();panel.addEventListener('close',closed);
  $('panel-body').onclick=event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.panel)openPanel(b.dataset.panel);else if(b.id==='keep-playing')panel.close();else if(b.id==='save-settings'){settings.pace=$('pace').value;settings.target=Number($('target').value);try{localStorage.setItem(SETTINGS,JSON.stringify(settings));}catch{warning='Settings could not be saved in this browser.';}panel.close();}else if(b.id==='new-match'&&performance.now()>=actionUntil){actionUntil=performance.now()+500;panel.close();newMatch();}};
  document.addEventListener('pointerdown',event=>{held.add(event.pointerId);clearTimeout(timer);},true);
  for(const type of ['pointerup','pointercancel'])document.addEventListener(type,event=>{held.delete(event.pointerId);schedule();},true);
  for(const type of ['blur','pagehide'])window.addEventListener(type,()=>{held.clear();clearTimeout(timer);generation++;});
  document.addEventListener('visibilitychange',()=>{held.clear();generation++;if(document.hidden)clearTimeout(timer);else schedule();});window.addEventListener('focus',schedule);
  HeartsTouch.install(document.body,()=>[generation,state.phase,state.turn,dialogKind],{selector:'button',unavailable:()=>false,selectable:'.help-text',consumeOutsideClick:true});
  load();render();
  if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').then(()=>navigator.serviceWorker.ready).then(()=>{offlineReady=true;$('save-status').textContent='Saved here · Offline ready';}).catch(()=>{});
})();
